services:
  - type: web
    name: prepgrid-1
    runtime: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://prepgrid-1-9bl2.onrender.com
      - key: CLIENT_URL
        value: https://prepgrid-pold.vercel.app
      - key: GOOGLE_REDIRECT_URI
        value: https://prepgrid-1-9bl2.onrender.com/api/auth/google/callback
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        value: 8bf68e8abecc1c6ef9ce223d30d0662d31f59386eaf0988b7fdc348367de20e2c21f47f35d5592f2a7456e8cc034b1754515588e22d1976e0bcfeca8abf7c9a0
      - key: JWT_REFRESH_SECRET
        value: c016db3389c206abcb8b07b9b377e9dc90d5d0cebb33194208a6e1bd33a4b5c4743c3948e253913d834230c349a252ab25a8b04fcea958f3f5e1c11dfa9ecffb
      - key: SESSION_SECRET
        value: 8bf68e8abecc1c6ef9ce223d30d0662d31f59386eaf0988b7fdc348367de20e2c21f47f35d5592f2a7456e8cc034b1754515588e22d1976e0bcfeca8abf7c9a0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: PISTON_URL
        value: https://emkc.org/api/v2/piston
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
